owner: vince978
repo: vince-monitoring

sites:
  - name: TBT Visa
    url: https://tbt-visa.srv951062.hstgr.cloud
  - name: TBT Flowers
    url: https://tbt-flowers.srv951062.hstgr.cloud
  - name: MF Dashboard
    url: https://mf.srv969505.hstgr.cloud
    expectedStatusCodes:
      - 401
  - name: Griot
    url: https://griot.srv969505.hstgr.cloud
    expectedStatusCodes:
      - 401
  - name: Pookie
    url: https://pookie.srv951062.hstgr.cloud
  - name: n8n
    url: https://n8n.srv969505.hstgr.cloud
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Audiomnes
    url: https://audiomnes.srv951062.hstgr.cloud
  - name: Pattaya AI
    url: https://pattaya.srv969505.hstgr.cloud
    expectedStatusCodes:
      - 401

status-website:
  baseUrl: /vince-monitoring
  name: Vince Services — Status
  introTitle: "Status des services en production"
  introMessage: Monitoring automatique via GitHub Actions. Mis a jour toutes les 5 minutes.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/vince978/vince-monitoring
